name: Compilación del documento .tex en la carpeta de informes
on:
  push:
  branches:
  -main # Detecta cambios en el repositorio principal para ejecutar el codigo

jobs:
   release_cv:
   name: "Ejecucion Informe LaTex"
   runs-on: ubuntu-latest

   steps:
    name: "Checkout maste"
    uses: actions/checkout@v1

    name: "Compilacion del Informe"
    uses: xu-cheng/latex-action@master
    with:
      root_file: Informes/Informe01

    name: "Revisión el PDF"
    run: 
      file Informe01.pdf | grep-q 'PDF'
    name: "Carga del PDF  a una URL fija"
    uses: "marvinpinto/action-automatic-releases@latest"
    with: 
      repo_token: "{{ secrets.PERSONAL_ACCESS_TOKEN}}"
      automatic_release_tag: "latest"
      prerelease: true
      title: "Carga"
      files:
        Informe01.pdf
