name: "Compilaci贸n del documento .tex en la carpeta de informes"

on:
  push:
    branches:
      - main

jobs:
  release_cv:
    name: "Ejecuci贸n Informe LaTeX"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout del repositorio"
        uses: actions/checkout@v1

      - name: "Compilaci贸n del Informe"
        uses: xu-cheng/latex-action@master
        with:
          root_file: Informes/Informe01.tex

      - name: "Revisi贸n del PDF"
        run: |
          file Informes/Informe01.pdf | grep -q 'PDF'

      - name: "Carga del PDF como release"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.TOKEN_ACTION }}
          automatic_release_tag: "latest"
          prerelease: true
          title: "Carga del informe"
          files: |
            Informe01.pdf
